# Generated by Django 4.2.16 on 2026-05-11 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(
                    max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(
                    blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False,
                 help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254,
                 unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=124, verbose_name='Имя')),
                ('surname', models.CharField(max_length=124, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=12, unique=True, validators=[
                 django.core.validators.RegexValidator(regex='^(\\+7|8)\\d{10}$')], verbose_name='Телефон')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub')),
                ('about', models.TextField(blank=True,
                 max_length=256, verbose_name='О себе')),
                ('avatar', models.ImageField(
                    upload_to='avatars/', verbose_name='Аватар')),
                ('is_active', models.BooleanField(
                    default=True, verbose_name='Активен')),
                ('is_staff', models.BooleanField(
                    default=False, verbose_name='Персонал')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                 related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.',
                 related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
