# Generated by Django 4.2.16 on 2026-05-11 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[
                                   django.core.validators.RegexValidator(regex='^(\\+7|8)\\d{10}$')], verbose_name='Телефон'),
        ),
    ]
