# Generated by Django 4.2.16 on 2026-05-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(
                blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
