# Generated by Django 4.2.16 on 2026-05-11 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200,
                 verbose_name='Название проекта')),
                ('description', models.TextField(
                    blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(
                    auto_now_add=True, verbose_name='Дата создания')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub')),
                ('status', models.CharField(choices=[
                 ('open', 'Открыт'), ('closed', 'Закрыт')], default='open', max_length=6)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(
                    blank=True, related_name='participated_projects', to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(blank=True,
                 related_name='projects', to='skills.skill')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
