MAX_LENGTH_NAME = 200
MAX_LENGTH_SKILL_NAME = 124
MAX_LENGTH_USER_NAME = 124
MAX_LENGTH_USER_SURNAME = 124
MAX_LENGTH_PHONE = 12
MAX_LENGTH_ABOUT = 256
MAX_LENGTH_STATUS = 6

STATUS_OPEN = 'open'
STATUS_CLOSED = 'closed'

STATUS_CHOICES = [
    (STATUS_OPEN, 'Открыт'),
    (STATUS_CLOSED, 'Закрыт'),
]

PAGINATE_BY = 12
SKILL_AUTOCOMPLETE_LIMIT = 10
