# Generated by Django 4.2.16 on 2026-05-14 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('name',), 'verbose_name': 'Навык', 'verbose_name_plural': 'Навыки'},
        ),
    ]
